[package]
name = "tuigreet"
version = "0.1.0"
authors = ["Antoine POPINEAU <antoine.popineau@appscho.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
getopts = "0.2.21"
greetd_ipc = { version = "0.6.0", features = ["sync-codec"] }
termion = "1.5.5"
tui = "0.9.5"
nix = "0.17.0"
textwrap = "0.12.0"
chrono = "0.4.11"
zeroize = "1.1.0"
rust-ini = "0.15.3"

[profile.release]
lto = true
