name: Continuous master build
on:
  push:
    branches:
      - master
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Create release
        uses: eine/tip@gha-tip
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cwd: ${{ github.workspace }}
          files: target/release/greetd-tui
